name: Windows Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-2022

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build
      run: |
        cargo build --release

    - name: Run
      run: |
        cargo run --release dummy.pdf

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: gh-mupdf-rs-win
        path: |
          target/release/*.exe
