name: Windows Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-2019

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Rust
      uses: dtolnay/rust-toolchain@stable

    - name: LLVM
      run: choco install -y llvm

    - name: Msbuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build
      run: |
        cargo build --release

    - name: Run
      run: |
        cargo run --release dummy.pdf
